config/routes.rb
Rails.application.routes.draw do
  get 'browse', to: 'posts#browse', as: :browse_posts
  post ':username/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':username/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications', to: 'notifications#index'
  root 'posts#index'
  devise_for :users, controllers: {registrations: 'registrations'}
  resources :posts
  resources :posts do
    resources :comments
    member do
      get 'like'
    end
  end
  # Using a symbol (:username) to enable dynamic parameter, since usernames change
  # HTTP verb, URI pattern, controller#action, prefix 
  get ':username', to: 'profiles#show', as: :profile
  get ':username/edit', to: 'profiles#edit', as: :edit_profile
  patch ':username/edit', to: 'profiles#update', as: :update_profile
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_many :posts
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  before_action :set_user
  before_action :authenticate_user!
  before_action :owned_profile, only: [:update, :edit]
  
  def show
    User.create(username: "Alfred")
    @posts = User.find_by(username: params[:username]).posts.order('created_at DESC')
  end
  
  def edit
  end
  
  def update
    if @user.update(profile_params)
      flash[:success] = "Your profile has been updated."
      redirect_to profile_path(@user.username)
    else
      @user.errors.full_messages
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end
  
  private
    def set_user
      @user = User.find_by(username: params[:username])
    end
    
    def profile_params
      params.require(:user).permit(:avatar, :bio)
    end
    
    def owned_profile
      unless current_user == @user
        flash[:alert] = "That profile doesn't belong to you!"
        redirect_to root_path
      end
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def current_user_is_following(current_user_id, followed_user_id)
    relationship = Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
    return true if relationship
  end
end

app/views/profiles/edit.html.erb
<!--<div class="container">-->
<!--  <h3 class="text-center">-->
<!--    <b>Change your profile image:</b>-->
<!--  </h3>-->
  
<!--  <div class="upload-preview">-->
<!--    <img />-->
<!--  </div>-->
<!--  <div class="upload-profile-image-button">-->
<!--    <input class="file" name="logo" type="file">-->
<!--  </div>-->
<!--</div>-->

<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= form_for @user, url: {action: "update"}, html: {multipart: true} do |f| %>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <h4>Change your profile image:</h4>
                <div class="img-circle">
                  <%= profile_avatar_select(@user) %>
                </div>
                <%= f.file_field :avatar, onChange: 'loadFile(event)' %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div class="form-group text-center">
                <h4>Update your bio:</h4>
                <%= f.text_area :bio, label: false, rows: 4 %>
              </div>
            </div>
          </div>
          <div class="form-group text-center">
            <%= f.submit "Update Profile", class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/profiles/follow.js.erb
$('#follow-button').attr('class', 'btn unfollow-button').text('Following')
.attr('href', "/<%= @user.username %>/unfollow_user").attr('id', 'unfollow-button');

app/views/profiles/show.html.erb
<div class="posts-wrapper">
  <div class="row profile-header">
    <div class="col-md-6">
      <div class="img-circle">
        <%= profile_avatar_select(@user) %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="username-and-follow">
        <h3 class="profile-username">
          <%= @user.username %>
        </h3>
        <span>
          <% if @user == current_user %>
            <%= link_to 'Edit Profile', edit_profile_path(@user.username), class: 'btn edit-button' %>
          <% else %>
            <% if current_user_is_following(current_user.id, @user.id) %>
              <%= link_to 'Following', unfollow_user_path, remote: true, class: 'btn unfollow-button', id: 'unfollow-button', method: :post %>
            <% else %>
              <%= link_to "Follow", follow_user_path, remote: true, class: 'btn follow-button', id: 'follow-button', method: :post %>
            <% end %>
          <% end %>
        </span>
      </div>
      <p class="profile-bio">
        <%= @user.bio %>
      </p>
      <div class="user-statistics">
        <p>
          <%= pluralize @user.posts.count, 'post' %>
        </p>
      </div>
    </div>
  </div>
</div>

<% if Post.count == 0 %>
  <div id="post-something-icon">
    <i class="fa fa-picture-o fa-5x text-center" aria-hidden="true"></i> 
  </div>
  <div id="post-something">
    <h4 class="text-center"><b>Post something!</b></h5>
  </div>
<% end %>

<% @posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>

<% if Post.count >= 3 %>
  <div id="paginator" class="text-center">
    <%= link_to 'LOAD MORE', posts_path, remote: true, id: 'load_more' %>
  </div>
<% end %>