config/routes.rb
Rails.application.routes.draw do
  get 'browse', to: 'posts#browse', as: :browse_posts
  post ':username/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':username/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications', to: 'notifications#index'
  root 'posts#index'
  devise_for :users, controllers: {registrations: 'registrations'}
  resources :posts
  resources :posts do
    resources :comments
    member do
      get 'like'
    end
  end
  # Using a symbol (:username) to enable dynamic parameter, since usernames change
  # HTTP verb, URI pattern, controller#action, prefix 
  get ':username', to: 'profiles#show', as: :profile
  get ':username/edit', to: 'profiles#edit', as: :edit_profile
  patch ':username/edit', to: 'profiles#update', as: :update_profile
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_votable
  
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  
  validates :user_id, presence: true
  validates :image, presence: true
  validates :caption, length: {minimum: 1, maximum: 300}, allow_blank: false
  
  has_attached_file :image, styles: {medium: "1000x500"}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
  
  scope :following, -> (following_users) {where user_id: following_users}
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :set_post, only: [:show, :edit, :update, :like, :destroy]
  before_action :authenticate_user!
  before_action :owned_post, only: [:edit, :update, :destroy]
  
  def new 
    @post = current_user.posts.build
  end
  
  def index
    @posts = Post.following(current_user.following).order('created_at DESC').page(params[:page]).per(3)
  end
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "New image posted!"
      redirect_to posts_path
    else
      flash_unsuccessful_message
      render :new
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @post.update(post_params)
      flash[:success] = "Image updated!"
      redirect_to post_path
      # redirect_to post_path(@post)
    else
      flash_unsuccessful_message
    end
  end
  
  def like 
    if @post.liked_by current_user
      respond_to do |format|
        format.html {redirect_to :back}
        format.js
      end
    end
  end
  
  def browse
    @posts = Post.all.order('created_at DESC').page(params[:page]).per(3)
  end
  
  def destroy
    if @post.destroy
      flash[:success] = "Image deleted!"
      redirect_to root_path
    else 
      flash_unsuccessful_message
      render :edit
    end
  end
  
  private
    def set_post
      @post = Post.find(params[:id])
    end
    
    def post_params
      params.require(:post).permit(:image, :caption)
    end
    
    def owned_post
      unless current_user == @post.user
        flash[:alert] = "This post doesn't belong to you!"
        redirect_to root_path
      end
    end
    
    def flash_unsuccessful_message
      # When rendering view, flash.now can be used; when redirecting to new view,
      # use flash without the now
      flash.now[:alert] = "Something went wrong!"
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def display_likes(post) 
    votes = post.votes_for.up.by_type(User)
    if votes.size >= 1 && votes.size <= 8 
      return list_likers(votes) 
    else 
      count_likers(votes)
    end
  end
  
  def liked_post(post)
    if current_user.voted_for? post
      return 'glyphicon-heart'
    else
      return 'glyphicon-heart-empty'
    end
  end
  
  private
    def list_likers(votes)
      usernames = []
      unless votes.blank?
        votes.voters.each do |voter|
          usernames.push(link_to voter.username, profile_path(voter.username), class: 'user-name')
        end
        usernames.to_sentence.html_safe + like_plural(votes)
      end
    end
    
    def count_likers(votes)
      vote_count = votes.size
      vote_count.to_s + ' likes'
    end
  
    def like_plural(votes)
      if votes.count >= 2
        return ' like this' 
      else
        return ' likes this'
      end
    end
end

app/views/posts/_form.html.erb
<div class="posts-wrapper">
  <div class="post">
    <div class="post-body">
      <div class="image-wrap">
        <%= form_image_select(@post) %>
        <%= simple_form_for @post, html: {multipart: true} do |f| %>
          <div class="row">
            <div class="col-md-12 text-center">
              <%= f.error_notification %>
            </div>
          </div>
          <br>
          <div class="container-fluid">
            <div class="form-group text-center">
              <%= f.input :image, label: false, required: true, input_html: {class: 'input-sm', onChange: 'loadFile(event)'} %>
              <%= f.input :caption, label: false, required: true, placeholder: "Enter a caption" %>
              <%= f.button :submit, class: "btn btn-primary btn-block" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
  

app/views/posts/_likes.html.erb
<div class="likes" id="likes_<%= post.id %>">
  <%= display_likes(post) %>
</div>

app/views/posts/_post.html.erb
<div class="container">
  <div class="row posts-wrapper">
    <div class="col-md-12">
      <div class="post">
      <div class="post-head">
        <div class="thumb-img">
        </div>
        <div class="user-name">
          <%= link_to post.user.username, profile_path(post.user.username) %>
        </div>
        <div class="time-ago">
          <%= time_ago_in_words(post.created_at) %>
        </div>
      </div>
      <div class="image center-block">
        <%= link_to (image_tag post.image.url(:medium), class: 'img-responsive'), post_path(post) %>
      </div>
      <div class="post-bottom">
        <%= render 'posts/likes', post: post %>
        <div class="caption">
          <div class="caption-content">
            <div class="user-name">
              <%= link_to post.user.username, profile_path(post.user.username) %>
            </div>
            <%= post.caption %>
          </div>
          <div class="comments" id="comments_<%= post.id %>">   
            <% if post.comments.any? %>
              <div class="paginator" id="#comments-paginator-<%= post.id %>">
                <% unless post.comments.count <= 4 %>
                  <%= link_to post_comments_path(post), remote: true, class: "more-comments", data: {post_id: "#{post.id}", type: "html"} do %>
                    <i class="fa fa-comments fa-3x" aria-hidden="true"></i>
                  <% end %>
                <% end %>
              </div>
              <br>
              <%= render post.comments.last(4), post: post %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="separator-border"></div>
      <div class="comment-like-form row">
        <div class="like-button">
          <%= link_to '', like_post_path(post.id), remote: true, id: "like_#{post.id}", class: "glyphicon #{liked_post post}" %>
        </div>
        <div class="comment-form">
          <%= form_for([post, post.comments.build], remote: true) do |f| %>
            <%= f.text_field :context, placeholder: 'Add a comment.', class: "comment_content", id: "comment_content_#{post.id}", style: "border: none; width: 84%" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
    </div>
</div>

app/views/posts/_post_dashboard.html.erb
<div id="posts">
  <%= render 'posts' %>
</div>

<div id="paginator">
  <%= link_to_next_page @posts, 'LOAD MORE', remote: true, id: 'load_more' %>
</div>

app/views/posts/_post_dashboard.js.erb
$('#posts').append("<%= escape_javascript(render 'posts') %>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote:
true, id: 'load_more')) %>");
if (!$('#load_more').length) {$('#paginator').remove();}

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
  <%= render 'post', post: post %>
<% end %>

app/views/posts/browse.html.erb
<%= render 'post_dashboard', posts: @posts %>

app/views/posts/edit.html.erb
<h3 class="update-photo-title text-center">Update Post</h3>
<%= render 'form' %>
<div class="edit-links text-center">
  <button type="button" class="btn btn-default btn-xs">
    <%= link_to "Delete", post_path(@post.id), method: :delete, data: {confirm: "Are you sure you want to delete this post?"} %>
  </button>
  |
  <button type="button" class="btn btn-default btn-xs">
    <%= link_to "Cancel", posts_path %>
  </button>
</div>

app/views/posts/index.html.erb
<%= render 'post_dashboard', posts: @posts %>

app/views/posts/index.js.erb
$('#posts').append("<%= escape_javascript(render 'posts') %>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote:
true, id: 'load_more')) %>");
if (!$('#load_more').length) {$('#paginator').remove();}

app/views/posts/like.js.erb
$("#like_<%= @post.id %>").removeClass('glyphicon-heart-empty').addClass('glyphicon-heart');
<%# Improve this by not making a call to server every time user likes or dislikes; instead, attach user's 
    username to the list of likers %>
$("#likes_<%= @post.id %>").html("<%= j (render partial: 'posts/likes', locals: {post: @post}) %>");

app/views/posts/new.html.erb
<div class="container">
  <h3 class="post-photo-title text-center">Post a Photo</h3>
  <%= render 'form' %>
</div>  


 

app/views/posts/show.html.erb
<%= render 'post', post: @post %>
  <% if @post.user.id == current_user.id %>
    <div class="text-center edit-links">
      <div class="btn btn-default btn-sm">
        <%= link_to "Edit", edit_post_path(@post.id), class: "edit" %>
      </div>
      |
      <div class="btn btn-default btn-sm">
        <%= link_to "Cancel", posts_path, class: "cancel" %> 
      </div>
    </div>
  <% else %>
    <div class="text-center edit-links">
      <div class="btn btn-default btn-sm">
        <%= link_to "Cancel", posts_path, class: "cancel" %> 
      </div>
    </div>
  <% end %>
</div>