config/routes.rb
Rails.application.routes.draw do
  get 'browse', to: 'posts#browse', as: :browse_posts
  post ':username/follow_user', to: 'relationships#follow_user', as: :follow_user
  post ':username/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through
  get 'notifications', to: 'notifications#index'
  root 'posts#index'
  devise_for :users, controllers: {registrations: 'registrations'}
  resources :posts
  resources :posts do
    resources :comments
    member do
      get 'like'
    end
  end
  # Using a symbol (:username) to enable dynamic parameter, since usernames change
  # HTTP verb, URI pattern, controller#action, prefix 
  get ':username', to: 'profiles#show', as: :profile
  get ':username/edit', to: 'profiles#edit', as: :edit_profile
  patch ':username/edit', to: 'profiles#update', as: :update_profile
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="navbar-container">
    
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header"> 
      <%= link_to root_path, class: "navbar-brand" do %>
        <span class="glyphicon glyphicon-camera"></span>
      <% end %>
    </div> 
    
    <div class="app-name">Picturesque</div>
    
    <ul class="nav navbar-nav navbar-right navbar-fixed-top">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
          <i class="fa fa-bars" aria-hidden="true"></i> 
        </a>
        <% if user_signed_in? %>
          <div class="notification-symbol">
            <%= render 'notifications/notification_dropdown' %>
          </div>
        <% end %>
        <ul class="dropdown-menu">
          <% if user_signed_in? %>
            <li><%= link_to "New Post", new_post_path %></li>
            <li><%= link_to "Browse", browse_posts_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Login", new_user_session_path %></li>
            <li><%= link_to "Register", new_user_registration_path %></li>
          <% end %>
        </ul>
      </li>
    </ul>
    
    <!-- Collect the nav links, forms, and other content for toggling -->
    <!--<div class="collapse navbar-collapse" id="bs-navbar-collapse-1">-->
    <!--  <ul class="nav navbar-nav navbar-right">-->
    <!--    <% if user_signed_in? %>-->
    <!--      <li><%= render 'notifications/notification_dropdown' %></li>-->
    <!--      <li><%= link_to "New Post", new_post_path %></li>-->
    <!--      <li><%= link_to "Browse", browse_posts_path %></li>-->
    <!--      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>-->
    <!--    <% else %>-->
    <!--      <li><%= link_to "Login", new_user_session_path %></li>-->
    <!--      <li><%= link_to "Register", new_user_registration_path %></li>-->
    <!--    <% end %>-->
    <!--  </ul>-->
    <!--</div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="navbar-content-divider">
  &nbsp
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Picturesque</title>
    <link href="https://fonts.googleapis.com/css?family=Nothing+You+Could+Do" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  
  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="container flash-container">
      <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: "alert alert-#{type}" do %>
          <% if type == "success" %>
            <i class="glyphicon glyphicon-ok"></i>
          <% else %>
            <i class="glyphicon glyphicon-exclamation-sign"></i>
          <% end %>
          <%= msg %>
        <% end %>
      <% end %>
    </div>
    
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>